# Generated by Django 3.2.8 on 2022-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(default='', max_length=11)),
                ('um_md5', models.CharField(max_length=128)),
                ('um_key', models.CharField(max_length=128)),
                ('um_eventId', models.CharField(max_length=128)),
                ('um_name', models.CharField(default='', max_length=128)),
                ('um_displayName', models.CharField(max_length=128)),
                ('um_status', models.CharField(max_length=10)),
                ('um_eventType', models.IntegerField(default=0)),
                ('um_countToday', models.IntegerField(default=0)),
                ('um_countYesterday', models.IntegerField(default=0)),
                ('um_deviceYesterday', models.IntegerField(default=0)),
                ('um_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UmKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(default='', max_length=11)),
                ('um_md5', models.CharField(max_length=128)),
                ('um_key', models.CharField(max_length=128)),
                ('um_name', models.CharField(max_length=20)),
                ('um_master', models.BooleanField(default=False)),
                ('um_status', models.IntegerField(default=0)),
                ('um_add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=11)),
                ('u_name', models.CharField(max_length=20)),
                ('u_pw', models.CharField(max_length=128)),
                ('u_phone', models.CharField(max_length=11)),
                ('u_email', models.CharField(max_length=128)),
                ('u_token', models.CharField(default='', max_length=128)),
                ('u_reg_time', models.DateTimeField(auto_now_add=True)),
                ('u_last_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=11)),
                ('uc_content_type', models.CharField(max_length=100)),
                ('uc_user_agent', models.CharField(max_length=500)),
                ('uc_token', models.CharField(max_length=100)),
                ('uc_token_haitang', models.CharField(max_length=100)),
                ('uc_cookie', models.CharField(max_length=5000)),
                ('uc_key_master', models.CharField(max_length=50)),
                ('uc_key_slaves', models.CharField(max_length=5000)),
                ('uc_add_time', models.DateTimeField(auto_now_add=True)),
                ('uc_update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
