# Generated by Django 3.2.8 on 2021-10-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um_key', models.CharField(max_length=128)),
                ('um_name', models.CharField(max_length=20)),
                ('um_master', models.BooleanField(default=False)),
                ('um_add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
