# Generated by Django 3.2.8 on 2021-12-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv_name', models.CharField(default='', max_length=128)),
                ('kv_key', models.CharField(max_length=128)),
                ('kv_value', models.CharField(max_length=5000)),
                ('kv_status', models.BooleanField(default=True)),
                ('kv_add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
