FROM ubuntu:18.04

COPY ./requirements.txt requirements.txt

RUN apt-get -y update --fix-missing \
    && apt-get install -y vim \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get install -y python3.8 python3-pip \
    && python3 -m pip install --upgrade pip \
    && python3 --version \
    && pip3 --version \
    && pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com \
    && apt-get install nginx -y \
    && apt-get install supervisor -y \
    && apt-get install make -y \
    && apt-get install gcc -y \
    && apt-get install wget -y \
    && wget https://download.redis.io/releases/redis-5.0.0.tar.gz \
    && tar -zxvf redis-5.0.0.tar.gz \
    && cd redis-5.0.0/ \
    && make PREFIX=/usr/local/redis install \
    && ln -s /usr/local/redis/bin/redis-server /usr/bin/redis-server